//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod notification;
pub mod rpc;
pub mod state;
pub mod yang;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
pub mod yang_gen {
    use holo_utils::bgp::{AfiSafi, Comm, ExtComm, Extv6Comm, LargeComm, Origin};
    use holo_utils::policy::DefaultPolicyType;
    use holo_utils::protocol::Protocol;
    pub use routing::control_plane_protocols::control_plane_protocol::bgp;

    use crate::neighbor::{PeerType, fsm};
    use crate::northbound::configuration::{ClusterId, InstanceTraceOption, NeighborTraceOption, PrivateAsRemove};
    use crate::packet::attribute::AsPathSegmentType;
    use crate::packet::iana::{Afi, CapabilityCode, Safi};
    use crate::packet::message::{AddPathMode, NotificationMsg};
    use crate::rib::{RouteIneligibleReason, RouteOrigin, RouteRejectReason};
    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use crate::instance::Instance;
        type Provider = Instance;
        include!(concat!(env!("OUT_DIR"), "/yang_ops.rs"));
    }
    pub mod config {
        use super::*;
        include!(concat!(env!("OUT_DIR"), "/yang_config.rs"));
    }
}
