//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

use std::fmt::Debug;
use std::pin::Pin;

use futures::stream::Stream;
use holo_utils::mac_addr::MacAddr;
use ipnetwork::IpNetwork;

use crate::Master;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(not(target_os = "linux"))]
mod null;

// Dataplane backend selected for this platform.
#[cfg(target_os = "linux")]
pub type Backend = linux::LinuxDataplane;
#[cfg(not(target_os = "linux"))]
pub type Backend = null::NullDataplane;

// Stream of events generated by the dataplane.
pub type DataplaneMonitor =
    Pin<Box<dyn Stream<Item = <Backend as Dataplane>::Event> + Send>>;

// Operations every dataplane backend provides to learn and program the system
// interfaces.
//
// The system interface state is learned only from the dataplane: the initial
// fetch and the monitor events feed it into the interface table. Programming
// operations are asynchronous: they may return before the dataplane is
// updated, and a failure is logged by the backend rather than reported to the
// caller.
pub(crate) trait Dataplane: Sized {
    // Event generated by the dataplane monitor.
    type Event: Debug + Send;

    // Initialize the dataplane.
    fn init() -> Self;

    // Start monitoring the dataplane, returning a stream of interface events.
    fn monitor() -> DataplaneMonitor;

    // Fetch interface and address information from the dataplane.
    async fn interfaces_fetch(master: &mut Master);

    // Process an event received from the dataplane monitor.
    fn process_msg(master: &mut Master, msg: Self::Event);

    // Change the administrative status of an interface.
    fn admin_status_change(&self, ifindex: u32, enabled: bool);

    // Change the MTU of an interface.
    fn mtu_change(&self, ifindex: u32, mtu: u32);

    // Create a VLAN interface on top of the given parent interface.
    fn vlan_create(&self, name: String, parent_ifindex: u32, vlan_id: u16);

    // Create a macvlan interface on top of the given parent interface.
    fn macvlan_create(
        &self,
        name: String,
        mac_address: Option<MacAddr>,
        parent_ifindex: u32,
    );

    // Delete an interface.
    fn iface_delete(&self, ifindex: u32);

    // Install an address on an interface.
    fn addr_install(&self, ifindex: u32, addr: &IpNetwork);

    // Uninstall an address from an interface.
    fn addr_uninstall(&self, ifindex: u32, addr: &IpNetwork);

    // Wait until all enqueued requests have been executed.
    fn flush(self);
}
