[package]
name = "holo-vrrp"
version.workspace = true
authors = ["Paul Wekesa <paul1tw1@gmail.com>"]
license.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
const-addrs.workspace = true
enum-as-inner.workspace = true
internet-checksum.workspace = true
ipnetwork.workspace = true
phf.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
yang5.workspace = true

holo-northbound = { path = "../holo-northbound", features = ["vrrp"] }
holo-protocol = { path = "../holo-protocol" }
holo-utils = { path = "../holo-utils" }
holo-yang = { path = "../holo-yang" }

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
nix.workspace = true
socket2.workspace = true

[dev-dependencies]
yang5 = { workspace = true, features = ["bundled"] }

holo-vrrp = { path = ".", features = ["testing", "deterministic"] }

[build-dependencies]
yang5 = { workspace = true, features = ["bundled"] }
holo-northbound = { path = "../holo-northbound", features = ["vrrp"] }
holo-yang = { path = "../holo-yang" }

[lints]
workspace = true

[features]
default = []
testing = [
  "holo-northbound/testing",
  "holo-protocol/testing",
  "holo-utils/testing",
]
deterministic = []
