//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod rpc;
pub mod state;

use holo_northbound::ProviderBase;

use crate::Master;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
pub mod yang_gen {
    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use crate::Master;
        type Provider = Master;
        include!(concat!(env!("OUT_DIR"), "/yang_ops.rs"));
    }
}

// ===== impl Master =====

impl ProviderBase for Master {
    fn top_level_node(&self) -> String {
        "/ietf-system:system".to_owned()
    }
}
