[package]
name = "holo-replay"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true

holo-bfd = { path = "../../holo-bfd" }
holo-bgp = { path = "../../holo-bgp" }
holo-ldp = { path = "../../holo-ldp" }
holo-igmp = { path = "../../holo-igmp" }
holo-isis = { path = "../../holo-isis" }
holo-rip = { path = "../../holo-rip" }
holo-ospf = { path = "../../holo-ospf" }
holo-protocol = { path = "../../holo-protocol" }
holo-utils = { path = "../../holo-utils" }
holo-vrrp = { path = "../../holo-vrrp" }

[lints]
workspace = true

[features]
default = []
testing = [
  "holo-bfd/testing",
  "holo-bgp/testing",
  "holo-ldp/testing",
  "holo-igmp/testing",
  "holo-isis/testing",
  "holo-rip/testing",
  "holo-ospf/testing",
  "holo-vrrp/testing",
]

[[bin]]
name = "replay"
path = "src/main.rs"
required-features = ["testing"]
