//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod rpc;
pub mod state;
pub mod yang;

use std::sync::LazyLock as Lazy;

use holo_northbound::ProviderBase;
use regex::Regex;

use crate::Master;
use crate::northbound::yang_gen::control_plane_protocol;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
#[allow(clippy::module_inception)]
pub mod yang_gen {
    pub use crate::northbound::yang_gen::routing::control_plane_protocols::control_plane_protocol;
    include!(concat!(env!("OUT_DIR"), "/yang_gen.rs"));
}

// ===== impl Master =====

impl ProviderBase for Master {
    fn top_level_node(&self) -> String {
        "/ietf-routing:routing".to_owned()
    }
}

// ===== regular expressions =====

// Matches on the protocol type and instance name of a YANG path.
static REGEX_PROTOCOLS_STR: Lazy<String> = Lazy::new(|| format!(r"{}\[type='(.+?)'\]\[name='(.+?)'\]*", control_plane_protocol::PATH));
pub static REGEX_PROTOCOLS: Lazy<Regex> = Lazy::new(|| Regex::new(&REGEX_PROTOCOLS_STR).unwrap());
