//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod rpc;
pub mod state;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
#[allow(clippy::module_inception)]
pub mod yang_gen {
    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use crate::Master;
        type Provider = Master;
        include!(concat!(env!("OUT_DIR"), "/yang_ops.rs"));
    }
}
