//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod notification;
pub mod rpc;
pub mod state;
pub mod yang;

use holo_northbound as northbound;
use holo_northbound::ProviderBase;
use holo_yang::ToYang;

use crate::instance::Instance;
use crate::version::{Ospfv2, Ospfv3, Version};

pub trait NorthboundVersion<V: Version> {
    const YANG_OPS_STATE: northbound::state::YangOps<Instance<V>>;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<V>>;

    fn validation_callbacks() -> Option<&'static northbound::configuration::ValidationCallbacks>;
    fn configuration_callbacks() -> &'static northbound::configuration::Callbacks<Instance<V>>;
}

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
#[allow(clippy::module_inception)]
pub mod yang_gen {
    pub use routing::control_plane_protocols::control_plane_protocol::ospf;
    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use super::*;
        pub mod ospfv2 {
            use crate::instance::Instance;
            use crate::version::Ospfv2;
            type Provider = Instance<Ospfv2>;
            include!(concat!(env!("OUT_DIR"), "/yang_ops_ospfv2.rs"));
        }
        pub mod ospfv3 {
            use crate::instance::Instance;
            use crate::version::Ospfv3;
            type Provider = Instance<Ospfv3>;
            include!(concat!(env!("OUT_DIR"), "/yang_ops_ospfv3.rs"));
        }
    }
}

// ===== impl Instance =====

impl<V> ProviderBase for Instance<V>
where
    V: Version,
{
    fn top_level_node(&self) -> String {
        format!("/ietf-routing:routing/control-plane-protocols/control-plane-protocol[type='{}'][name='{}']/ietf-ospf:ospf", V::PROTOCOL.to_yang(), self.name)
    }
}

// ===== impl Ospfv2 =====

impl NorthboundVersion<Self> for Ospfv2 {
    const YANG_OPS_STATE: northbound::state::YangOps<Instance<Self>> = yang_gen::ops::ospfv2::YANG_OPS_STATE;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<Self>> = yang_gen::ops::ospfv2::YANG_OPS_RPC;

    fn validation_callbacks() -> Option<&'static northbound::configuration::ValidationCallbacks> {
        Some(&configuration::VALIDATION_CALLBACKS_OSPFV2)
    }

    fn configuration_callbacks() -> &'static northbound::configuration::Callbacks<Instance<Self>> {
        &configuration::CALLBACKS_OSPFV2
    }
}

// ===== impl Ospfv3 =====

impl NorthboundVersion<Self> for Ospfv3 {
    const YANG_OPS_STATE: northbound::state::YangOps<Instance<Self>> = yang_gen::ops::ospfv3::YANG_OPS_STATE;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<Self>> = yang_gen::ops::ospfv3::YANG_OPS_RPC;

    fn validation_callbacks() -> Option<&'static northbound::configuration::ValidationCallbacks> {
        Some(&configuration::VALIDATION_CALLBACKS_OSPFV3)
    }

    fn configuration_callbacks() -> &'static northbound::configuration::Callbacks<Instance<Self>> {
        &configuration::CALLBACKS_OSPFV3
    }
}
