//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod rpc;
pub mod state;

use std::sync::LazyLock as Lazy;

use holo_northbound::ProviderBase;
use regex::Regex;

use crate::Master;
use crate::northbound::yang_gen::interfaces;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
pub mod yang_gen {
    include!(concat!(env!("OUT_DIR"), "/yang_gen.rs"));
}

// ===== impl Master =====

impl ProviderBase for Master {
    fn top_level_node(&self) -> String {
        "/ietf-interfaces:interfaces".to_owned()
    }
}

// ===== regular expressions =====

// Matches on the protocol type and instance name of a YANG path.
static REGEX_VRRP_STR: Lazy<String> = Lazy::new(|| format!(r"{}\[name='(.+?)'\](?:/ietf-ip:(?:ipv4|ipv6))?/(?:ietf-vrrp|holo-vrrp):vrrp/*", interfaces::interface::PATH));
pub static REGEX_VRRP: Lazy<Regex> = Lazy::new(|| Regex::new(&REGEX_VRRP_STR).unwrap());
