//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod rpc;
#[allow(unreachable_code)]
pub mod state;
pub mod yang;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
pub mod yang_gen {
    pub use routing::control_plane_protocols::control_plane_protocol::igmp;

    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use crate::instance::Instance;
        type Provider = Instance;
        include!(concat!(env!("OUT_DIR"), "/yang_ops.rs"));
    }
}
