//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod rpc;
pub mod state;
pub mod yang;

use holo_northbound::ProviderBase;
use holo_utils::protocol::Protocol;
use holo_yang::ToYang;

use crate::instance::Instance;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
pub mod yang_gen {
    pub use crate::northbound::yang_gen::routing::control_plane_protocols::control_plane_protocol::igmp;
    include!(concat!(env!("OUT_DIR"), "/yang_gen.rs"));
}

// ===== impl Instance =====

impl ProviderBase for Instance {
    fn top_level_node(&self) -> String {
        format!(
            "/ietf-routing:routing/control-plane-protocols/control-plane-protocol[type='{}'][name='{}']/ietf-igmp-mld:igmp",
            Protocol::IGMP.to_yang(),
            self.name
        )
    }
}
