//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod notification;
pub mod rpc;
pub mod state;
pub mod yang;

use holo_northbound::ProviderBase;
use holo_utils::protocol::Protocol;
use holo_yang::ToYang;

use crate::master::Master;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
pub mod yang_gen {
    pub use routing::control_plane_protocols::control_plane_protocol::bfd;

    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use crate::master::Master;
        type Provider = Master;
        include!(concat!(env!("OUT_DIR"), "/yang_ops.rs"));
    }
}

// ===== impl Master =====

impl ProviderBase for Master {
    fn top_level_node(&self) -> String {
        format!("/ietf-routing:routing/control-plane-protocols/control-plane-protocol[type='{}'][name='main']/ietf-bfd:bfd", Protocol::BFD.to_yang(),)
    }
}
