//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod rpc;
pub mod state;
pub mod yang;

use holo_northbound as northbound;
use holo_northbound::ProviderBase;
use holo_yang::ToYang;

use crate::instance::Instance;
use crate::version::{Ripng, Ripv2, Version};

// RIP version-specific code.
pub trait NorthboundVersion<V: Version> {
    const YANG_OPS_STATE: northbound::state::YangOps<Instance<V>>;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<V>>;

    fn validation_callbacks() -> Option<&'static northbound::configuration::ValidationCallbacks>;
    fn configuration_callbacks() -> &'static northbound::configuration::Callbacks<Instance<V>>;
}

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
#[allow(clippy::module_inception)]
pub mod yang_gen {
    pub use routing::control_plane_protocols::control_plane_protocol::rip;
    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use super::*;
        pub mod ripv2 {
            use crate::instance::Instance;
            use crate::version::Ripv2;
            type Provider = Instance<Ripv2>;
            include!(concat!(env!("OUT_DIR"), "/yang_ops_ripv2.rs"));
        }
        pub mod ripng {
            use crate::instance::Instance;
            use crate::version::Ripng;
            type Provider = Instance<Ripng>;
            include!(concat!(env!("OUT_DIR"), "/yang_ops_ripng.rs"));
        }
    }
}

// ===== impl Instance =====

impl<V> ProviderBase for Instance<V>
where
    V: Version,
{
    fn top_level_node(&self) -> String {
        format!("/ietf-routing:routing/control-plane-protocols/control-plane-protocol[type='{}'][name='{}']/ietf-rip:rip", V::PROTOCOL.to_yang(), self.name)
    }
}

// ===== impl Ripv2 =====

impl NorthboundVersion<Self> for Ripv2 {
    const YANG_OPS_STATE: northbound::state::YangOps<Instance<Self>> = yang_gen::ops::ripv2::YANG_OPS_STATE;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<Self>> = yang_gen::ops::ripv2::YANG_OPS_RPC;

    fn validation_callbacks() -> Option<&'static northbound::configuration::ValidationCallbacks> {
        Some(&configuration::VALIDATION_CALLBACKS_RIPV2)
    }

    fn configuration_callbacks() -> &'static northbound::configuration::Callbacks<Instance<Self>> {
        &configuration::CALLBACKS_RIPV2
    }
}

// ===== impl Ripng =====

impl NorthboundVersion<Self> for Ripng {
    const YANG_OPS_STATE: northbound::state::YangOps<Instance<Self>> = yang_gen::ops::ripng::YANG_OPS_STATE;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<Self>> = yang_gen::ops::ripng::YANG_OPS_RPC;

    fn validation_callbacks() -> Option<&'static northbound::configuration::ValidationCallbacks> {
        Some(&configuration::VALIDATION_CALLBACKS_RIPNG)
    }

    fn configuration_callbacks() -> &'static northbound::configuration::Callbacks<Instance<Self>> {
        &configuration::CALLBACKS_RIPNG
    }
}
