//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod notification;
pub mod rpc;
pub mod state;
pub mod yang;

use holo_northbound::ProviderBase;
use holo_utils::protocol::Protocol;
use holo_yang::ToYang;

use crate::instance::Instance;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
#[allow(clippy::module_inception)]
pub mod yang_gen {
    pub use crate::northbound::yang_gen::routing::control_plane_protocols::control_plane_protocol::mpls_ldp;
    include!(concat!(env!("OUT_DIR"), "/yang_gen.rs"));
}

// ===== impl Instance =====

impl ProviderBase for Instance {
    fn top_level_node(&self) -> String {
        format!(
            "/ietf-routing:routing/control-plane-protocols/control-plane-protocol[type='{}'][name='{}']/ietf-mpls-ldp:mpls-ldp",
            Protocol::LDP.to_yang(),
            self.name
        )
    }
}
