//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod notification;
pub mod rpc;
pub mod state;
pub mod yang;

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
#[allow(clippy::module_inception)]
pub mod yang_gen {
    pub use routing::control_plane_protocols::control_plane_protocol::mpls_ldp;

    use crate::neighbor::LabelAdvMode;
    use crate::northbound::state::AdvertisementType;
    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use crate::instance::Instance;
        type Provider = Instance;
        include!(concat!(env!("OUT_DIR"), "/yang_ops.rs"));
    }
}
